### ISSUE TITLE
Error occurred during async invocation: MQTT: Callback threw an exception on update: [json.exception.type_error.302] type must be number, but is string

### ISSUE THREAD

**Issue by patopat** [eclipse-velocitas/vehicle-app-cpp-template#53]
Hi,

There is a mistake in the tutorial for the dummy payload, the datatype for the requestId is a string and an int is expected in the sample.

It should be: 
```json
{ "position": 300, "requestId": 123}
```
Regards,
Pat

**Comment by MP91** [comment]
Hey @patopat, 
good catch! 

We will fix this in https://github.com/eclipse-velocitas/velocitas-docs/pull/99
