### ISSUE TITLE
[Bug]: Cannot use name except sampleapp

### ISSUE THREAD

**Issue by MC00614** [eclipse-velocitas/vehicle-app-cpp-template#69]
### Severity

Medium

### What release version, tag or commit-hash did you use?

30029a90d3392addba65c3e4a9c7fdff7eef5fe4

### Current Behavior

Due to unupdated version of `devenv-runtimes` in [.velocitas.json](https://github.com/eclipse-velocitas/vehicle-app-cpp-template/blob/main/.velocitas.json)
I can just use app name as `sampleapp`.
Please refer this issue [devenv-runtimes](https://github.com/eclipse-velocitas/devenv-runtimes/commit/83411f068b789b67e18e037308fbd21d70192f20)

### Steps to Reproduce

1. Change name of application in Template from sampleapp
2. Due to the preset of name in devenv-runtimes, we cannot use any other name

### Expected Behavior

We need to use other application name

### Possible Solution

Change 
From
            "name": "devenv-runtimes",
            "version": "v2.2.1"
to
            "name": "devenv-runtimes",
            "version": "v2.2.2"

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by MC00614** [comment]
Also, I have some problem of CI process in `initial commit` - automated-tests

```sh

Run devcontainers/ci@v0.3
Starting...
Installing @devcontainers/cli...
** Installing @devcontainers/cli
/usr/bin/bash -c npm install -g @devcontainers/cli@0

added 1 package in 660ms
🏗️ build container
🏃 start container
🚀 Run command in container
0s
Post job cleanup.
Error: imageName is required to push images

```

I think this is because version devenv-github-workflows which is 4.1.1 now
So, I modify it 4.1.2 for CI.

The reason why I do this is in Python Template, 4.1.2 works and it is also already updated.

**Comment by MP91** [comment]
@MC00614 could you please clarify if the issue is solved when you update the packages to the latest versions?

In the meantime we also updated the versions in the template directly.

**Comment by MP91** [comment]
Since there is no response and we updated all the dependencies, we assume that the bug is fixed. 

@MC00614  please open a new issue if you notice something else.
